dist: trusty

sudo: false  # builds will run on Docker infrastructure!

language: scala

scala:
  - 2.10.6
  - 2.11.8
  - 2.12.1
  
jdk:
  - oraclejdk8
  - openjdk8
  
branches:
  only:
    - master
    - develop
    
script:
  - sbt clean compile
  - sbt coverage test functional:test

after_success:
  - sbt coverageReport
  - sbt codacyCoverage
  - "[[ $TRAVIS_BRANCH == \"develop\" ]] && { sbt 'set credentials += Credentials(\"Sonatype Nexus Repository Manager\", \"oss.sonatype.org\", System.getenv(\"SONATYPE_USERNAME\"), System.getenv(\"SONATYPE_PASSWORD\"))'; sbt publish; };"
  
env:
  global:
    - secure: "V7vhWyyrZMQOf1ANHKHgbjUK6XlztR/fG5o6MxW/MUmdEuR05HaswS10IXs+GEXkduqRXTl4JNPMG2rnc5RAjZmLOxMsvPvhzvSFM9lr9SAHHNRQpthWtsqTc2XGGzEk61ARGHpaEbPH+N+XYB0mdu1x39ZE9TWUj5+F5wxoBH2ZGfFRDzppeIvFT2EmhfS51b9X5on2fM0Dw1uB1PzK1OR9XL42wFXeOtf125s7Sw6dAIDWQ4dyB7XYpflZxK8H3hvsripNQ4X6z503Od7NlkWF1wkfpdk/B6unJFiu3YlpI7XArYigL89OXNRA4gtiUQeayYmEHzVPfN3bLkRv2gm7+kwPiMlHXRvQ/Cz5wCzS0CF88WlSrQCGabcsRtC4YLXEfh+MORji/3aa7o1IYLjHgfe7N8uxjBCv0wtUVcnbk69HgPNqm6RSPnil9eH92FVONJfAowo8AvLwLU2A+iGYyl8fmRrQGz/OLCrvpJpsJzQzwE67K1VI+pTovpL2yjL+imuQmmCje3Wq9drxwcYHisTln57mpImtw8rgBg/bHxczuvH8XEwzqOGIJi3jP4mtX1PEqtpek5T0khcm8O2GPlZtT1RNGV+NMptFFTctier5I5ww20FazoI1P9PjFtike3MiiBCFMBJYlIUoweuTLMi5agohYOsU9Ju/Z3Q="
    - secure: "ISnOaNhvgCtG6Z0/PbafHvYDzotQpbJXpAqgF/Z8zcI4kP/mgP7MXiJ9EBDHE/NjQBV9HLKdGCkQtdisZqC8VgkvZuJxbeKlLd3/XW5xkJv28OK9aSTfBlzZTa0FDn+yzV8Tk1dqnIvPRbtCyxpr4+3Wp59MTppXvM6bRGIjbKRukryEeVEhQPRY74oQNMnHm+688smFXd5kAqhFMy/xx7e8dq1WVB24F70ywOYHPs5eHBsVqJCdf5U5YMbCoybR4pFyFnaUO/lkzBPH5sgPfeePMINmC7i+Bgg5PIgtGWjhKWP2WSfkQfca6/yu/Q7mwMg43bM4j0IqVghZa3LH5TWVTxsOlsbsJvw2Xkv0kAlBCsyoaiAZlW4T/BC9DDV7zT2ltMadbpcurzdIKp2mxfTR4MT7PqQxSt9lAS89akQb1DmjHxT8KQ5MDUy/++ReAmJib/aDW+h675MoAa3dZt2Ljj+sdKs2u/G2Mk9updcipOAxrzy3rpyTNuVJLo31LNDAX0ujZQbQA32wFjQF9fvJOuLZsazjCPG48opkayXQE+YdK2okW9MN+zestyI9VYh4jh/LJcgEczYpqJl5HKl8La7AbE6iO8mQ09146NK1+dkueekN/mp23ONEfG9gJpptAcN0U0yDo7ucrOZVwa5Jky64gEq1zQZDJ8O0Exc="
    - secure: "rZcWtSAdfFc9glRDhv2uHJPovVnpnYDH6UdU/5Ym1YJaFtVzEZPO/mj6N9k27nsONYxZXDcrJbjS8ZL/DrJeRMYTvMjji7NIpFAVwheTm2FdnyyjtZl1x/o/2bqmpX29Gog3XBWb+2mzSWi8gSsPY7bJrYLVHs7P31z6/BaMzHAHIN8WqjY6VrDuzo6ildp9Hjrp7aya2M/m0EAIi9WljfLXyLbTvq9nlguHT0IdnO61AZD5Ygy2gukeSbcIMrP8J1HLKBSGei5PKWIgSO4kYzMcLJhuqhZ2r8c2OgjcYp8BeR1WDOdkQyIjM9qo2c4AJLxJeZL5Iwr5qFuD4UVnneLlIZI7D43jmu9AGKxEvGgLZ2vaSV00RCv7yY9a4dQaQ8gY7ith+q3PiRRfwMQQmAALVdZPzTQPAD5klKa4y5/mw39KwmXI0dnXmftm8d6SaJITOnh+q5Dn5BIKoNKMP0ZoY/FufjnX0qgveFCfE2Ez68fVMEfuN1bhcQ59VY3XgtVfvLNcDPrmWXTrQdLTz1XPnNdhk+IOlw6QtLgCuSguFyYAqrV36OdxcHnFNLOAV8P8uqUejANohNgNqnN9PxSY0OdELI6wd4S1soSxsSKuZN3THCKcguxvbKJ0shzh8v9PnNgC/L9OBB2Yd/XFk8fPpEYM5iupenzRyzMNCLg="


before_cache:
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/
