dist: trusty

sudo: false  # builds will run on Docker infrastructure!

language: scala

scala:
  - 2.10.6
  - 2.11.8
  - 2.12.1
  
jdk:
  - oraclejdk8
  - openjdk8
  
branches:
  only:
    - master
    - develop
    
script:
  - sbt clean compile
  - sbt coverage test functional:test

after_success:
  - sbt coverageReport
  - sbt codacyCoverage
  - "[[ $TRAVIS_BRANCH == \"develop\" ]] && { sbt 'set credentials += Credentials(\"Sonatype Nexus Repository Manager\", \"oss.sonatype.org\", System.getenv(\"SONATYPE_USERNAME\"), System.getenv(\"SONATYPE_PASSWORD\"))'; sbt publish; };"
  
env:
  global:
    - secure: "V7vhWyyrZMQOf1ANHKHgbjUK6XlztR/fG5o6MxW/MUmdEuR05HaswS10IXs+GEXkduqRXTl4JNPMG2rnc5RAjZmLOxMsvPvhzvSFM9lr9SAHHNRQpthWtsqTc2XGGzEk61ARGHpaEbPH+N+XYB0mdu1x39ZE9TWUj5+F5wxoBH2ZGfFRDzppeIvFT2EmhfS51b9X5on2fM0Dw1uB1PzK1OR9XL42wFXeOtf125s7Sw6dAIDWQ4dyB7XYpflZxK8H3hvsripNQ4X6z503Od7NlkWF1wkfpdk/B6unJFiu3YlpI7XArYigL89OXNRA4gtiUQeayYmEHzVPfN3bLkRv2gm7+kwPiMlHXRvQ/Cz5wCzS0CF88WlSrQCGabcsRtC4YLXEfh+MORji/3aa7o1IYLjHgfe7N8uxjBCv0wtUVcnbk69HgPNqm6RSPnil9eH92FVONJfAowo8AvLwLU2A+iGYyl8fmRrQGz/OLCrvpJpsJzQzwE67K1VI+pTovpL2yjL+imuQmmCje3Wq9drxwcYHisTln57mpImtw8rgBg/bHxczuvH8XEwzqOGIJi3jP4mtX1PEqtpek5T0khcm8O2GPlZtT1RNGV+NMptFFTctier5I5ww20FazoI1P9PjFtike3MiiBCFMBJYlIUoweuTLMi5agohYOsU9Ju/Z3Q="
    - secure: "B6QFcwVht/TO0FK+IRHe2NkFdY6HPEPfFYiQsblk64HBOffkZAkISdKHZl61ydZU9YMLG24YJRbESfLSBPdyOF9ieck2kefFhHyXKnEG77U+oHYRLiyiO8AhNZuxqmVVlh4/WORHHQ0hASDfJQSOzOz1s734NJKmM7Bo+bcaCmeV3xWDNRU8/NvuxtiXZrvmVw7ByG6IAlMe31gFAsdmEezfwskl6860bX/u82iJoO8N5PzH5HWjBgP7I31S1W38LUD9Kbz1HITCmyRkCKC7A/oLgZvwNiYbgpeEETI7IHuSI2NlDN583k2KhVaQBrgnQGNHaR4ghc1QQUDyknXJfX4L2AUquZpxQdO5rDZvUhd9Pg7/9WmQifVnuoLCgJyZSocRdZjXT1feGDvRpd9dtkEAxVxDTM2WmSxbCMDVeHn0UaAG+TDLAojN5WFjApqHS7YvSuHQgLgmZ/wtaROs4CnFKkZaEZr1fwdqVb12IYagTHpu8QfhkdNs9EbzPA8wB6QbLX51wk6Oew8O4+EzbpiYH4/hHW+i7a7CtfveyJ2D0VDrXv5RDCu3tiaUJSGCRlTkt0tai/54GrGYqUp5bRRJ9AWeCOyVnbHZcOf4tHygNy63/Ss+FAmRGe5ocFbvu2DppetX8c6jm3fy6zJyKlCYeH7bY8hEgwtozUa3oRM="
    - secure: "q7kaM38ksaCzwsczVmUK3ghjf8pF1War27jXR6ZRr1IhnMlvSuAAEiuYTaBMU8XyoAT0/s0JuzJrrU0tOEVOJ/4oAGx/vkVc6lvDnooEOUTYneKsiEr5eWCZtETJUoKHOuQzbFIoshksAZztq8qt9ctJwOlIlP/Qsy0bbxVhcqInQtggh8CY3pCS7mMPyp1VyPoo51QrsvCzocJN3LA4k4/vvL+WNM95bU8t4XjyN9mE4DiiPE0Yokg2/8+dDv8UwKtrOAb+dMrn4P6+1iCl1td5gOVSLo+S+TLlJTJamxNbkpm8rTxXC6URSuIZX+EXG0mezrwaLYTFHi+UJ1AjGdXs6EZYMGvmSFTEUEZithqzvCnl6kqmrfjbh3dProkWUqHOn1S8tiRjhVrVESA5LuqbkkKOB2tKjxHJBdKaMjFbFpcyvTArm8QxjAzwV0Wm3uZw4uLBj6tsI9R8iYvRSrn1NNhsC4OiUN340x9EapiH+MDl14VcqT47DC5xp+7tCKiD37NFMcYWUQqMFwtPj8SWDBv+ibAUpIEqF4mNzXHqjBcZz63LQ8glkIgTBkY6mdcp2lg6n870GAMPDfhtHLzRHEDc9d1cLAmcLCXUiKwbHo0CyTG6cj6LOkBnvVvsTolxj8ugQZEHEZH5G3xTg+iMraVZ8PX2IHreFg+8HKU="


before_cache:
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/
